name: aula_hasura_shelf_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.1 <3.0.0'


dependencies:
 hasura_connect: ^3.0.6
 shelf: ^1.2.0 
 shelf_modular: ^1.0.0-dev.6
 jaguar_jwt: ^3.0.0

 
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0